---
  metaData: 
    author: "d3fkon"
    git-repo: "https://github.com/d3fkon/demonstration1"
    approval: 
      approved-by: "d3fkon"
      approval-date: 1564468151127
  job: 
    job-name: "d3fkonxdemonstration1"
    config: 
      pre-unit-test: "no"
      post-unit-test: "yes"
      dev: "no"
      prod: "no"
      fresh: "yes"
